server:
  port: 8083


spring:
  jackson:
    time-zone: Asia/Seoul

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://j9b309.p.ssafy.io:3306/i9?serverTimezone=Asia/Seoul
    username: i9B309
    password: ***REMOVED***

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update



  # mongoDB
  data:
    mongodb:
      uri: mongodb://j9b309.p.ssafy.io:20000
      database: finance

